### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rmoriz** [Youscribe/kvm-cookbook#9]
As far as I can see this repo differs from the latest version on chef-supermarket e.g. kvm::host_tuning is still kvm::host-tuning.

Maybe you can cut a release for the current master branch. thank you

**Comment by predominant** [comment]
Bump

**Comment by guilhem** [comment]
Have to work on it ;)

**Comment by PierreRambaud** [comment]
Gentle ping!

**Comment by guilhem** [comment]
FIxed by 1047cacf740152c7d84b49bf12b0ed0b0022fe95

Yes I put "4" instead of "9" in commit message... had a hard night ^^

**Comment by PierreRambaud** [comment]
Thanks ;)
